### Authenticate the user
POST http://localhost:9090/sample-graphql/authenticate
Content-Type: application/json

{
  "username": "administrator",
  "password": "098e190d-3e10-4eec-aa4c-6c092528b15d"
}

### Verify if the user is authenticated and is the administrator
GRAPHQL http://localhost:9090/sample-graphql/graphql
Authorization: Bearer eyJhbGciOiJSUzUxMiJ9.eyJpc3MiOiJodHRwczovL3NwcmluZ2Jsb29tLmRldi9pc3N1ZXIiLCJzdWIiOiJhZG1pbmlzdHJhdG9yIiwiZXhwIjoxNzQ5ODUyNTg5LCJpYXQiOjE3NDk4NDg5ODksImp0aSI6ImI1NjVkMjA2LWNkNGUtNDZjYi1iMjQ2LWVjMGI3NDM3YmM4YSIsImF1dGhvcml0aWVzIjpbIlJPTEVfQURNSU5JU1RSQVRPUiJdfQ.ij9I6dOAFe12QzHE2KpzCOEwp23fwrc6tJ6qPUzCKCwiHtQ-SFxQQqOjS9Zwu1YFKW78rPK8WTb_VJpYnw9P0YWfALi6rDfYpD3-bkO-kVWFnxcvba2YMoT2sQef5J9qJ6uyJSBkU_bWRE8J0fJf2wEPd-gkEYLDjgEgCeI5PD6IS4dyv9O7-YnAT89PjXBZHoLqKuEohzaf2XVP3Z_fE2iZa8rGF8WTsb4Tneyz5McVuG2-jQNPgMmkD8F2HrjTmSRHSoNzSnDiAwV-0nAGJrrPfqI3VdK2zavOSS2DAMTOZ4uxIgcb70Ve_R7GKH9HQId4YZ7NuESpmLmOERRON9_8jzD3AzgAfqDm0wUl91JSSPkJv5y5XPv3NkKQ6pIa1azAifDU7pPXQwDQXpil-sBTMAmoDbija2NjpVyH8BRJxVVCH8L6mmSv3OKo7pB5098Vmc9XIO3XSf1qxmupLtkzo5dOXy3yVPi8JL_rXQbPfGCakMKeAxDFZZpx45h97VEbieiVeAL6ai_N0iJMDEMFLoKSKyokmfBkWgGZMTEOw-7qGZNtILbnDM9BYNTVmzJOfSmKahRl8iarH7EpJkP0WePy9i78WNVzN10KZkq0kew4TgLGle8sb0J5hx9YHtIrG0dQaQYyvthSYbtHnDQz8mBvUnBPA__iQRQuZt4

query isAdministrator {
    isAdministrator
}

## ################################################################################################################# ##

### Retrieve Internationalized Message (Bloqueante)
GRAPHQL http://localhost:9090/sample-graphql/graphql
Accept-Language: pt-BR,pt;q=0.5
Authorization: Bearer eyJhbGciOiJSUzUxMiJ9.eyJpc3MiOiJodHRwczovL3NwcmluZ2Jsb29tLmRldi9pc3N1ZXIiLCJzdWIiOiJhZG1pbmlzdHJhdG9yIiwiZXhwIjoxNzQ5ODUyNTg5LCJpYXQiOjE3NDk4NDg5ODksImp0aSI6ImI1NjVkMjA2LWNkNGUtNDZjYi1iMjQ2LWVjMGI3NDM3YmM4YSIsImF1dGhvcml0aWVzIjpbIlJPTEVfQURNSU5JU1RSQVRPUiJdfQ.ij9I6dOAFe12QzHE2KpzCOEwp23fwrc6tJ6qPUzCKCwiHtQ-SFxQQqOjS9Zwu1YFKW78rPK8WTb_VJpYnw9P0YWfALi6rDfYpD3-bkO-kVWFnxcvba2YMoT2sQef5J9qJ6uyJSBkU_bWRE8J0fJf2wEPd-gkEYLDjgEgCeI5PD6IS4dyv9O7-YnAT89PjXBZHoLqKuEohzaf2XVP3Z_fE2iZa8rGF8WTsb4Tneyz5McVuG2-jQNPgMmkD8F2HrjTmSRHSoNzSnDiAwV-0nAGJrrPfqI3VdK2zavOSS2DAMTOZ4uxIgcb70Ve_R7GKH9HQId4YZ7NuESpmLmOERRON9_8jzD3AzgAfqDm0wUl91JSSPkJv5y5XPv3NkKQ6pIa1azAifDU7pPXQwDQXpil-sBTMAmoDbija2NjpVyH8BRJxVVCH8L6mmSv3OKo7pB5098Vmc9XIO3XSf1qxmupLtkzo5dOXy3yVPi8JL_rXQbPfGCakMKeAxDFZZpx45h97VEbieiVeAL6ai_N0iJMDEMFLoKSKyokmfBkWgGZMTEOw-7qGZNtILbnDM9BYNTVmzJOfSmKahRl8iarH7EpJkP0WePy9i78WNVzN10KZkq0kew4TgLGle8sb0J5hx9YHtIrG0dQaQYyvthSYbtHnDQz8mBvUnBPA__iQRQuZt4

query getAuthenticatedUsernameIfPresent {
    getAuthenticatedUsernameIfPresent
}

### Retrieve Internationalized Message (Bloqueante)
GRAPHQL http://localhost:9090/sample-graphql/graphql
Accept-Language: pt-BR,pt;q=0.5

query getInternationalizedMessage($messageId: String!) {
    getInternationalizedMessage(messageId: $messageId)
}

{
  "messageId": "testObject.withNullId"
}

### Retrieve Internationalized Message (Simple Suspended)
GRAPHQL http://localhost:9090/sample-graphql/graphql
Accept-Language: pt-BR,pt;q=0.5

query getSimpleSuspendInternationalizedMessage($messageId: String!) {
    getSimpleSuspendInternationalizedMessage(messageId: $messageId)
}

{
  "messageId": "testObject.withNullId"
}

### Retrieve Internationalized Message (Nested Suspended)
GRAPHQL http://localhost:9090/sample-graphql/graphql
Accept-Language: pt-BR,pt;q=0.5

query getNestedSuspendInternationalizedMessage($messageId: String!) {
    getNestedSuspendInternationalizedMessage(messageId: $messageId)
}

{
  "messageId": "testObject.withNullId"
}

### Retrieve Internationalized Message (Async)
GRAPHQL http://localhost:9090/sample-graphql/graphql
Accept-Language: pt-BR,pt;q=0.5

query getAsyncInternationalizedMessage($messageId: String!) {
    getAsyncInternationalizedMessage(messageId: $messageId)
}

{
  "messageId": "testObject.withNullId"
}

### Retrieve Paginated Response
GRAPHQL http://localhost:9090/sample-graphql/graphql

query getPaginatedResponse {
    getPaginatedResponse {
        totalPages
        totalElements
        content
    }
}

## ################################################################################################################# ##

### Throw Exception
GRAPHQL http://localhost:9090/sample-graphql/graphql

query throwException {
    throwException
}

### Throw Throwable
GRAPHQL http://localhost:9090/sample-graphql/graphql

query throwThrowable {
    throwThrowable
}

### Throw Application Exception
GRAPHQL http://localhost:9090/sample-graphql/graphql

query throwApplicationException {
    throwApplicationException
}

### Throw Undeclared Throwable Exception
GRAPHQL http://localhost:9090/sample-graphql/graphql

query throwUndeclaredThrowableException {
    throwUndeclaredThrowableException
}

## ################################################################################################################# ##

### Create test object without validation
GRAPHQL http://localhost:9090/sample-graphql/graphql

mutation createTestObjectWithoutValidation($testObject: TestObjectInput!) {
    createTestObjectWithoutValidation(testObject: $testObject) {
        name
        cellphone
    }
}

{
  "testObject": {
    "name": "Felipe",
    "cellphone": "(41) 98765-4321"
  }
}

### Test if typed validation on input was called automatically
GRAPHQL http://localhost:9090/sample-graphql/graphql

mutation validateInputTestObject($testObject: TestObjectInput!) {
    validateInputTestObject(testObject: $testObject) {
        name
    }
}

{
  "testObject": {
    "name": "Felipe"
  }
}

### Test if typed validation on return was called automatically
GRAPHQL http://localhost:9090/sample-graphql/graphql

mutation validateInputAndReturnTestObject($testObject: TestObjectInput!) {
    validateInputAndReturnTestObject(testObject: $testObject) {
        name
    }
}

{
  "testObject": {
    "name": "Test"
  }
}
